import type { IProject } from "./types";

export const MOCK_PROJECTS: IProject[] = [
  {
    id: "PRJ-1001",
    name: "Website Redesign",
    owner: "Alice Johnson",
    priority: "High",
    status: "In Progress",
    progress: 65,
    members: 5,
    dueDate: "2026-08-15",
  },
  {
    id: "PRJ-1002",
    name: "Mobile App Launch",
    owner: "David Kim",
    priority: "High",
    status: "Planning",
    progress: 10,
    members: 8,
    dueDate: "2026-09-30",
  },
  {
    id: "PRJ-1003",
    name: "API Migration",
    owner: "Priya Patel",
    priority: "Medium",
    status: "In Progress",
    progress: 40,
    members: 4,
    dueDate: "2026-07-28",
  },
  {
    id: "PRJ-1004",
    name: "Customer Portal",
    owner: "Marcus Lee",
    priority: "Medium",
    status: "Review",
    progress: 85,
    members: 6,
    dueDate: "2026-07-20",
  },
  {
    id: "PRJ-1005",
    name: "Internal Dashboard",
    owner: "Sofia Rossi",
    priority: "Low",
    status: "Completed",
    progress: 100,
    members: 3,
    dueDate: "2026-06-10",
  },
  {
    id: "PRJ-1006",
    name: "Payment Gateway Integration",
    owner: "Alice Johnson",
    priority: "High",
    status: "In Progress",
    progress: 55,
    members: 7,
    dueDate: "2026-08-05",
  },
  {
    id: "PRJ-1007",
    name: "Marketing Analytics",
    owner: "David Kim",
    priority: "Low",
    status: "Planning",
    progress: 5,
    members: 2,
    dueDate: "2026-10-12",
  },
  {
    id: "PRJ-1008",
    name: "Security Audit",
    owner: "Priya Patel",
    priority: "High",
    status: "Review",
    progress: 90,
    members: 4,
    dueDate: "2026-07-18",
  },
];
